### ISSUE TITLE
elasticity: implement dual solve

### ISSUE THREAD

**Issue by bgranzow** [bgranzow/goal#10]
Solve the dual problem:
(\nabla z, \sigma(w) ) = J'[u^H](w)
for multiple quantities of interest J.

**Comment by bgranzow** [comment]
While debugging the evaluator `elast_ev_von_mises`, I noticed that the compiler (gcc 6.2.0) hates everything about:
```
auto val = FadTypeVariable(elem,ip);
```
best to explicitly use:
```
ScalarT val = FadTypeVariable(elem,ip);
```

**Comment by ibaned** [comment]
nooo  `auto` was supposed to be perfect....

**Comment by bgranzow** [comment]
https://www.youtube.com/watch?v=HUBWxiu5cOo

To be more clear, i did something like this:
```
auto s1 = (FadVariable1  - FadVariable2);
s1 *= s1;
```
which the compiler hated on the second line.
```
ScalarT s1 = (FadVariable1 - FadVariable2);
s1 *= s1;
```
worked though. I think there's some scary stuff going on in the Sacado SFad class that caused this.
