### ISSUE TITLE
Make Indexer an abstract base class

### ISSUE THREAD

**Issue by bgranzow** [bgranzow/goal#42]
Issue [#24] is making it clear that it would be convenient to have classes like:
`StridedIndexer`, `BlockIndexer`, and `MixedIndexer` all inherit from an abstract `Indexer` base class. This will probably be painful. Hopefully it's worth it.

**Comment by bgranzow** [comment]
@shamsallah, @JustinClough

This will break backwards compatibility for some APIs.
In particular, check out this commit: 7e146cce4fca4ffefab9d842b4e2485be999f1cd
for the changes that will need to be made for your physics class and traction evaluator.

**Comment by ibaned** [comment]
`goal` has users ! huzzah !

**Comment by bgranzow** [comment]
the snake oil is working!
