### ISSUE TITLE
Allow SCOREC/core builds as either stand-alone or in Trilinos

### ISSUE THREAD

**Issue by bgranzow** [bgranzow/goal#49]

**Comment by ibaned** [comment]
... doesn't this happen already ?

**Comment by bgranzow** [comment]
SCOREC/core can absolutely be built either in Trilinos or as a stand-alone package. When it is built as a Trilinos package this line fails:

https://github.com/bgranzow/goal/blob/master/cmake/Dependencies.cmake#L2

This issue is just meant to add some additional logic to check that if that line fails, then we must have SCOREC as a Trilinos package, using some logic like this:

https://github.com/bgranzow/goal/blob/master/cmake/Dependencies.cmake#L18

**Comment by ibaned** [comment]
oh sorry I thought this was a SCOREC/core issue. didn't even check the repo name. carry on.

**Comment by bgranzow** [comment]
done in 5c9c99c and b8dd03d
